### ISSUE TITLE
No Blocks Showing up

### ISSUE THREAD

**Issue by ughary** [Despical/Commons#3]
Hello, I love this minigame, but I noticed that the blocks aren't showing up. Just the "punch me" text appears. I tried changing the blocks on the config file but then the plugin itself stops working so I play using the text only, but it is difficult to do so without the blocks.

**Comment by Despical** [comment]
Hi there,

What is your server software (Spigot, Paper, Purpur, etc.) and version? Are there any exceptions in the console?

One last word, the absence of a public repo for Whack Me does not give you permission to create issues on unrelated repositories. Next time, please contact me on SpigotMC.

Best regards,
Despical

**Comment by Despical** [comment]
@ughary Any updates?

**Comment by Despical** [comment]
Contact me on SpigotMC, closing the issue.
